spring:
  application:
    name: Chatbot

  ai:
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1024
        indexType: IVF_FLAT
        metricType: COSINE

    ollama:
      chat:
        options:
          model: llama3.2:latest
      embedding:
        options:
          model: mxbai-embed-large
